# Generated by Django 3.0.3 on 2020-05-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_blogs',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_confessions',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
    ]
