# Generated by Django 3.0.3 on 2020-05-22 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Confession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessionpost',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
