# Generated by Django 3.0.3 on 2020-05-22 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Confession', '0002_confessionpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confessionpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
