# Generated by Django 3.0.3 on 2020-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0003_auto_20200514_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confessionpost',
            name='display_name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
